### ISSUE TITLE
Issues with all versions above 1.14.1 - Response code was 404, expected 200,path: "api/v2/monitor/system/sensor-info"

### ISSUE THREAD

**Issue by jbergquist** [bluecmd/fortigate_exporter#190]
In issue #158 you got the same issue, I however run a weee bit newer firmware. What I did was recompile the docker image with the newest version and I had to revert back to 1.14.1 to get the exporter to work again.

It throws me off a bit, since when I access api/v2/monitor/system/ I get the definition for sensor-info in the output.
I deleted everything about the api key user, and set it up again according to the documentation.. but still no dice. 

What did I miss?

$> curl -k https://URL/api/v2/monitor/system/?access_token=myToken

```
    {
      "path":"system",
      "name":"sensor-info",
      "action":"select",
      "supported":false,
      "access_group":"sysgrp.cfg",
      "summary":"Retrieve system sensor status.",
      "request":{
        "http_method":"GET"
      },
      "response":{
        "type":"object"
      }
    }
```

$> curl -k https://URL/api/v2/monitor/system/sensor-info?access_token=myToken

```
  "path":"system",
  "name":"sensor-info",
  "action":"",
  "serial":"SERIAL",
  "version":"v7.2.0",
  "build":1157,
  "status":"error",
  "http_status":404`
```
  
$> cat authfile

```
"https://URL":
  token: myToken
  probes:
    exclude:
      - Wifi
```

**Comment by jbergquist** [comment]
OK, so I got the status 404 on server-info but the exporter still scraped the correct info and put it in prometheus... so I get an error in the logs, but I still get the metrics.

**Comment by bluecmd** [comment]
This is sort of expected if your Fortigate does not expose any sensor information - the scrape of that will fail, and since it's part of the default collection you will get a warning about that. It's not great UX but I am not really sure what else we should do unless start adding a list of model exclusions.

In the Usage section this behavior is somewhat referenced and a workaround is presented, https://github.com/bluecmd/fortigate_exporter#usage - have you tried that?

**Comment by jbergquist** [comment]
I am a moron, thank you for pointing my ape brain in the right direction. Works like a charm.
