### ISSUE TITLE
Create Probe Interface

### ISSUE THREAD

**Issue by Med2190** [bluecmd/fortigate_exporter#218]
Hello community,

First of all I would like to thank you for the development of the export.

I would like to monitor the bandwidth speed of my interfaces (in Mbps) and not "bytes".

Do you think it is possible to create a probe for this? 

If so, how? 

Thanks in advance.

**Comment by bluecmd** [comment]
Hi! Since the underlying counter exposed by the Fortigate device is in bytes, it is the most correct way to export this data. However, if you wish to display or calculate using bits, it's quite easy to do so in Prometheus by just doing a `fortigate_...._bytes * 8` to get the bits.

**Comment by thenodon** [comment]
@Med2190 when writing exporter we try to adhere to https://prometheus.io/docs/instrumenting/writing_exporters/. Among other great advice here is one related to your question:

_Metrics must use base units (e.g. seconds, bytes) and leave converting them to something more readable to graphing tools. No matter what units you end up using, the units in the metric name must match the units in use. Similarly, expose ratios, not percentages. Even better, specify a counter for each of the two components of the ratio._
So even if the underlying metrics is exposed as ms or Mbps the exporter should recalculate that to sec and bps before emitting the metrics.

**Comment by satare** [comment]
Hi, i work with @Med2190 in the same company and i encouraged him to create this issue to contribute to OSS by it self.

The problem here is that we do have a metric that represent the total amount of data in bytes (wich is fine) but we have trouble making it match the fortigate web UI that shows the data throughtput (Bytes/sec) can someone help us with this prom query? 

Forti interface : we can see a High spot around 125Mbps @ 11:10
![fortiInterface](https://user-images.githubusercontent.com/6135457/236423422-ffa2b3bd-6a41-46c4-b846-9d4d3ea6146c.png)

Grafana Visualisation : Same curve but with wrong scale, the high spot is only around 45Mb/s
![GrafanaInterface](https://user-images.githubusercontent.com/6135457/236423577-53c2c0f3-3390-423b-94df-f3c49e6785dc.PNG)

we don't know how to make it match ...

**Comment by bluecmd** [comment]
When talking about packet speeds you always have to consider "over what window of time?". Usually this is never presented to the operator, but it is due to how math and digital systems work always present.

E.g. if a software reads the total packet byte counter 1 time every second, you will get the average speed over 1 second. In your case, you use rate() over [1m] which means you are plotting the average 1-minute rate. If you want more peaks in your graphs, you can switch to using `irate` instead which uses the lowest window possible with the samples available to Prometheus. If that's still not peaky for you, you will have to poll the Fortigate devices more often by decreasing the scrape_interval in Prometheus to get more samples to calculate over.

**Comment by satare** [comment]
Ok, Thanks, 

So in our case (we want to make a grafana panel as precise as possible) : we can scrape the data more often (not really what i want to do, because we don't really need it otherwise), OR do the maths in our query to "almost" match the forti webui (after all, this is just a visualisation).  

Am i right ?

**Comment by bluecmd** [comment]
Correct!
