### ISSUE TITLE
Build the Docker image on RHEL ?

### ISSUE THREAD

**Issue by yatanasov** [bluecmd/fortigate_exporter#40]
Hi,

It seems like it is not possible to build the Docker image of the exporter on RHEL:

` docker build -t fortigate_exporter .
Sending build context to Docker daemon 965.1 kB
Step 1/13 : FROM golang:latest as builder
Error parsing reference: "golang:latest as builder" is not a valid repository/tag: invalid reference format`

Could you provide ready made images or document how to build the docker image on RHEL ?

Thank you!

**Comment by secustor** [comment]
Do you using the Docker packages provided by RH for RHEL7?    
In that case the Docker version is stuck on 1.13.1 which is a 3 year old version of Docker which does not allow multistage builds.

You have 3 options as long there are no prebuilt images as suggested in #38:

- use buildah ( the RH alternative to `docker build` ) 
- Install Docker CE instead of the RH version of Docler
- Build the image locally and then export the image in a tar, copy it to the target host and then import it then again. https://www.jamescoyle.net/how-to/1512-export-and-import-a-docker-image-between-nodes

**Comment by bluecmd** [comment]
You can also try to run the fresh built `quay.io/bluecmd/fortigate_exporter:latest`. It is right now untested but might unblock you.

**Comment by yatanasov** [comment]
Thanks ! : ))
